#!/usr/bin/env python3
"""
Generate parameter grid file for MESA parameter studies on SLURM clusters

This script creates a parameter grid file that can be used with
02_array_mesa_run.slurm or 04_large_grid.slurm to run many MESA models
with different parameter combinations.

Usage:
    python3 generate_parameter_grid.py > parameter_grid.txt

Output format:
    Each line contains space-separated key=value pairs:
    initial_mass=7.0 Zbase=0.02 mixing_length_alpha=2.0
    initial_mass=10.0 Zbase=0.02 mixing_length_alpha=2.0
    ...

Author: NuGrid Team
License: BSD 3-Clause
"""

import itertools
import sys


def generate_grid():
    """
    Define parameter ranges and generate all combinations

    Customize this function to create your desired parameter grid.
    """

    # ==========================================================================
    # CONFIGURE YOUR PARAMETER GRID HERE
    # ==========================================================================

    # Example 1: Small grid for testing (30 models)
    # masses = [1.0, 2.0, 5.0]
    # metallicities = [0.001, 0.02]
    # alphas = [1.8, 2.0, 2.2]
    # overshoot = [0.0, 0.1]

    # Example 2: Medium grid for initial studies (150 models)
    masses = [1.0, 1.5, 2.0, 2.5, 3.0, 4.0, 5.0, 7.0, 10.0, 15.0]
    metallicities = [0.001, 0.004, 0.008, 0.014, 0.02]
    alphas = [1.8, 2.0, 2.2]

    # Example 3: Large grid for comprehensive studies (600 models)
    # Uncomment to use:
    # masses = [1.0, 1.2, 1.5, 1.8, 2.0, 2.5, 3.0, 4.0, 5.0, 7.0,
    #           10.0, 12.0, 15.0, 20.0, 25.0]
    # metallicities = [0.0001, 0.001, 0.004, 0.008, 0.014, 0.02, 0.03]
    # alphas = [1.6, 1.8, 2.0, 2.2, 2.4]
    # rotation = [0.0, 0.3, 0.5]

    # ==========================================================================
    # GENERATE GRID
    # ==========================================================================

    # Two-parameter grid (mass x metallicity x alpha)
    grid = []
    for mass, Z, alpha in itertools.product(masses, metallicities, alphas):
        params = {
            'initial_mass': mass,
            'Zbase': Z,
            'mixing_length_alpha': alpha
        }
        grid.append(params)

    # Three-parameter grid example (uncomment to use):
    # grid = []
    # for mass, Z, alpha, rot in itertools.product(masses, metallicities, alphas, rotation):
    #     params = {
    #         'initial_mass': mass,
    #         'Zbase': Z,
    #         'mixing_length_alpha': alpha,
    #         'new_rotation_flag': '.true.' if rot > 0 else '.false.',
    #         'set_initial_omega_div_omega_crit': rot
    #     }
    #     grid.append(params)

    return grid


def format_parameter_line(params):
    """
    Format parameter dictionary as space-separated key=value string

    Args:
        params (dict): Parameter dictionary

    Returns:
        str: Formatted parameter line
    """
    return ' '.join(f"{key}={value}" for key, value in params.items())


def main():
    """Main function"""

    # Generate grid
    grid = generate_grid()

    # Print header (as comment)
    print(f"# Parameter grid for MESA studies")
    print(f"# Total models: {len(grid)}")
    print(f"# Generated by: generate_parameter_grid.py")
    print(f"#")
    print(f"# Format: key=value key=value ...")
    print(f"# Use with: sbatch --array=1-{len(grid)} 02_array_mesa_run.slurm")
    print(f"#")

    # Print each parameter combination
    for i, params in enumerate(grid, start=1):
        line = format_parameter_line(params)
        print(line)

    # Print summary to stderr
    print(f"\nGenerated {len(grid)} parameter combinations", file=sys.stderr)

    # Print parameter statistics to stderr
    print(f"\nParameter ranges:", file=sys.stderr)

    # Collect all unique values for each parameter
    all_params = {}
    for params in grid:
        for key, value in params.items():
            if key not in all_params:
                all_params[key] = set()
            all_params[key].add(value)

    # Print statistics
    for key, values in sorted(all_params.items()):
        sorted_values = sorted(values)
        print(f"  {key}: {len(values)} values", file=sys.stderr)
        if len(sorted_values) <= 10:
            print(f"    {sorted_values}", file=sys.stderr)
        else:
            print(f"    [{sorted_values[0]}, ..., {sorted_values[-1]}]", file=sys.stderr)


if __name__ == '__main__':
    main()
