# Ansible Inventory for NuDocker Cluster
# Auto-generated by Terraform

[all:vars]
ansible_user=ubuntu
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# Central Manager (HTCondor Collector/Negotiator/Schedd + SLURM Controller + NFS Server)
[central_manager]
${central_manager_ip} ansible_host=${central_manager_ip} private_ip=${central_manager_private}

# HTCondor Execute Nodes
[htcondor_execute]
%{ for ip in htcondor_execute_ips ~}
${ip} ansible_host=${ip}
%{ endfor ~}

# SLURM Compute Nodes
[slurm_compute]
%{ for ip in slurm_compute_ips ~}
${ip} ansible_host=${ip}
%{ endfor ~}

# Group all HTCondor nodes
[htcondor:children]
central_manager
htcondor_execute

# Group all SLURM nodes
[slurm:children]
central_manager
slurm_compute

# All nodes in the cluster
[cluster:children]
central_manager
htcondor_execute
slurm_compute
